name: Static Code Analysis

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:

defaults:
  run:
    shell: pwsh

jobs:
  powershell-static-code-analysis:
    name: PowerShell Static Code Analysis
    strategy:
      matrix:
        machine-type: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.machine-type }}

    steps:
    - shell: bash
      run: |
        curl -LO https://github.com/jsoref/Lombiq-Utility-Scripts/archive/refs/issue/OSOE-150-zip.zip https://github.com/Lombiq/PowerShell-Analyzers/archive/8b33f9fbcfce40052cf6a3651e4d14e0d42aab40.zip
        unzip OSOE-150-zip.zip
        (mkdir Analyzers && cd Analyzers && unzip ../8b33f9fbcfce40052cf6a3651e4d14e0d42aab40.zip)
        rm OSOE-150-zip.zip 8b33f9fbcfce40052cf6a3651e4d14e0d42aab40.zip
    
    
    - name: Windows PowerShell Static Code Analysis
      run: |
        if ($Env:RUNNER_OS -ne 'Windows') 
        {
            Write-Output "This step is only for Windows. The current runner is $Env:RUNNER_OS so it's skipped."
            exit 0
        }
        powershell .\Analyzers\Lombiq.Analyzers.PowerShell\Invoke-Analyzer.ps1 -ForGitHubActions
    
    - name: PowerShell 7+ Static Code Analysis
      if: always() # Even if the above fails, let's check both.
      run: .\Analyzers\Lombiq.Analyzers.PowerShell\Invoke-Analyzer.ps1 -ForGitHubActions
